SELECT DISTINCT MP.ANIO_MES_OPERACION AS PERIODO
	, P.TIP_DOCUM_CLI
	, P.COD_DOCUM_CLI
FROM(
	SELECT ANIO_MES_OPERACION AS PERIODO
		, TIP_DOCUM_CLI
		, COD_DOCUM_CLI
		, NUM_POLIZA
	FROM CUBOS.MP_CRM_POLIZAS
	WHERE ANIO_MES_OPERACION = 202302
		AND COD_CIA = 1
		AND COD_RAMO IN (114, 116)
		AND EST_POLIZA IN ('REHABILITADA', 'VIGENTE')
		AND ((TIP_DOCUM_CLI = 'RUC' AND COD_DOCUM_CLI LIKE '10%') OR TIP_DOCUM_CLI IN ('DNI', 'CEX', 'PEX'))) P
INNER JOIN(
	SELECT *
	FROM CUBOS.MP_CRM_POLIZAS
	WHERE ANIO_MES_OPERACION = 202303
		AND COD_CIA = 1
		AND COD_RAMO IN (114, 116)
		AND EST_POLIZA IN ('ANULADA','EXPIRADA')
		AND ((TIP_DOCUM_CLI = 'RUC' AND COD_DOCUM_CLI LIKE '10%') OR TIP_DOCUM_CLI IN ('DNI', 'CEX', 'PEX'))) MP
	ON P.NUM_POLIZA = MP.NUM_POLIZA
	
-- Script para extraer datos de clientes que cuenten con pólizas de autos pero no con pólizas de salud

SELECT DISTINCT ANIO_MES_OPERACION AS PERIODO
	, TIP_DOCUM_CLI AS TIP_DOCUM
	, COD_DOCUM_CLI AS COD_DOCUM
FROM CUBOS.MP_CRM_POLIZAS P
WHERE ANIO_MES_OPERACION = 202312
	AND COD_CIA = 1
	AND COD_RAMO = 301
	AND EST_POLIZA IN ('VIGENTE', 'REHABILITADA')
	AND ((TIP_DOCUM_CLI = 'RUC' AND COD_DOCUM_CLI LIKE '10%') OR TIP_DOCUM_CLI IN ('DNI', 'CEX', 'PEX'))
	AND NOT EXISTS(
		SELECT 1
		FROM CUBOS.MP_CRM_POLIZAS S
		WHERE S.ANIO_MES_OPERACION = 202312
			AND S.COD_CIA = 1
			AND S.COD_RAMO IN (114, 116)
			AND S.EST_POLIZA IN ('VIGENTE', 'REHABILITADA')
			AND S.TIP_DOCUM_CLI = P.TIP_DOCUM_CLI
			AND S.COD_DOCUM_CLI = P.COD_DOCUM_CLI)
	AND NOT EXISTS(
		SELECT 1
		FROM SGA.EPSAF00@PRD S
		WHERE S.NDIDNTDD = P.COD_DOCUM_CLI)